/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.si1105.utils;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;

import org.junit.Test;

public class Executor {

	@Test
	public void run() throws Exception {
		Path dir = Paths.get("C:\\Users\\信也\\Documents");
		List<String> files = Arrays.asList("img20210104_13521098.jpg");
		for (int i = 0; i < files.size(); i++) {
			long date = 19960114090000l + i;
			String fileName = dir.resolve(files.get(i)).toString();
			Utils.touch(fileName, String.valueOf(date));
		}
	}
}
